services:
  - type: web
    name: react-frontend
    env: docker
    docker:
      dockerfilePath: ./vchat_frontend/Dockerfile  # Path to the Dockerfile for the frontend
      context: ./vchat_frontend                      # Context directory for the frontend
    routes:
      - type: rewrite
        name: frontend
        path: /
        destination: http://localhost:3000  # Adjust based on your React app's URL
    plan: free
    autoDeploy: true

  - type: web
    name: spring-backend
    env: docker
    docker:
      dockerfilePath: ./vchat_backend/Dockerfile  # Path to the Dockerfile for the backend
      context: ./vchat_backend                      # Context directory for the backend
    routes:
      - type: rewrite
        name: backend
        path: /api
        destination: http://localhost:8088  # Adjust based on your backend API URL
    plan: free
    autoDeploy: true

